# -*- coding: utf-8 -*-
"""gfg.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NNRRrz2O2cGxSW9wQ2uW0cjHYQ39KYOc
"""





import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from xgboost import XGBRegressor
from sklearn.linear_model import LinearRegression
from sklearn import metrics

exercise_data = pd.read_csv('/content/exercise.csv')
exercise_data.head()

calories = pd.read_csv('/content/calories.csv')
calories.head()

calories_data = pd.concat([exercise_data, calories['Calories']], axis=1)
calories_data.head()

calories_data.shape

X = calories_data.drop(columns=['User_ID','Height','Weight',  'Body_Temp' , 'Calories'], axis=1)
Y = calories_data['Calories']



print(X)

X.replace({"Gender":{'male':0,'female':1}}, inplace=True)

X.head()

print(Y)



X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=2)
print(X.shape, X_train.shape, X_test.shape)

model =  LinearRegression()

model.fit(X_train, Y_train)

test_data_prediction = model.predict(X_test)
print(test_data_prediction)

print(Y_test)

model.score(X_test, Y_test)

! pip install tensorflow



! pip install joblib

import joblib

filename = 'gfg_project.joblib'
joblib.dump(model, filename)

models = joblib.load('gfg_project.joblib')

models.predict([[0,60,30,105]])